# Generated by Django 5.1.15 on 2026-08-20 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopperprofile",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shoppers",
                to="merchants.merchant",
            ),
        ),
        migrations.AddField(
            model_name="shopperprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shopper_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="shopper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="accounts.shopperprofile",
            ),
        ),
    ]
