# Generated by Django 5.1.15 on 2026-08-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_merchant_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopperprofile",
            name="reward_points",
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
