# Generated by Django 5.1.15 on 2026-08-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_shopperprofile_reward_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopperprofile",
            name="gender",
            field=models.CharField(blank=True, default="Male", max_length=32),
        ),
        migrations.AddField(
            model_name="shopperprofile",
            name="profile_photo",
            field=models.TextField(blank=True, default=""),
        ),
    ]
