# Generated by Django 5.1.15 on 2026-08-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_shopperprofile_reward_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopperprofile',
            name='address_mismatch_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopperprofile',
            name='high_value_cod_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopperprofile',
            name='multiple_variant_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopperprofile',
            name='successful_deliveries',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
