# Generated by Django 5.1.15 on 2026-08-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_shopperprofile_address_mismatch_count_and_more'),
        ('accounts', '0005_shopperprofile_gender_shopperprofile_profile_photo'),
    ]

    operations = [
    ]
