# Generated by Django 5.1.15 on 2026-08-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rewardwallet_userpreference_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopperprofile',
            name='avg_items_per_order',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AddField(
            model_name='shopperprofile',
            name='avg_order_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='shopperprofile',
            name='damage_claim_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopperprofile',
            name='damage_no_evidence_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopperprofile',
            name='duplicate_return_request_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopperprofile',
            name='reason_change_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopperprofile',
            name='rejected_return_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopperprofile',
            name='replacement_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopperprofile',
            name='same_product_return_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopperprofile',
            name='size_exchange_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopperprofile',
            name='total_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='shopperprofile',
            name='total_refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
