"""
PDF Invoice Generator for ReturnGuard
Generates professional invoices for successful orders
"""
import io
import re
from datetime import datetime
from decimal import Decimal

from django.conf import settings
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, mm
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer,
    PageBreak, HRFlowable,
)
from reportlab.pdfgen import canvas


# Brand color
BRAND_COLOR = colors.HexColor('#4f46e5')
BRAND_LIGHT = colors.HexColor('#eef2ff')
HEADER_BG = colors.HexColor('#4f46e5')
ROW_ALT = colors.HexColor('#f8fafc')
BORDER_COLOR = colors.HexColor('#e2e8f0')
TEXT_MUTED = colors.HexColor('#64748b')
TEXT_DARK = colors.HexColor('#1e293b')


class NumberedCanvas(canvas.Canvas):
    """Canvas that adds page numbers to each page."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            super().showPage()
        super().save()

    def draw_page_number(self, page_count):
        self.setFont("Helvetica", 8)
        self.setFillColor(TEXT_MUTED)
        text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(A4[0] - 0.5 * inch, 0.35 * inch, text)
        self.drawString(0.5 * inch, 0.35 * inch, "Generated by ReturnGuard")


class InvoicePDFGenerator:
    """Generate professional PDF invoices with full order details."""

    def __init__(self, order, invoice):
        self.order = order
        self.invoice = invoice
        self.merchant = order.merchant
        self.customer = order.user
        self.payment = getattr(order, 'payment', None)
        self.buffer = io.BytesIO()
        self.styles = getSampleStyleSheet()
        self._setup_styles()

    def _setup_styles(self):
        """Create custom paragraph styles."""
        self.title_style = ParagraphStyle(
            'InvoiceTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=BRAND_COLOR,
            spaceAfter=4,
            leading=28,
        )
        self.section_header = ParagraphStyle(
            'SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=10,
            textColor=TEXT_DARK,
            spaceBefore=10,
            spaceAfter=5,
            leading=13,
        )
        self.normal = ParagraphStyle(
            'InvoiceNormal',
            parent=self.styles['Normal'],
            fontSize=9,
            textColor=TEXT_DARK,
            leading=13,
        )
        self.small = ParagraphStyle(
            'InvoiceSmall',
            parent=self.styles['Normal'],
            fontSize=8,
            textColor=TEXT_MUTED,
            leading=11,
        )

    def generate(self):
        """Generate PDF and return bytes."""
        doc = SimpleDocTemplate(
            self.buffer,
            pagesize=A4,
            rightMargin=0.5 * inch,
            leftMargin=0.5 * inch,
            topMargin=0.5 * inch,
            bottomMargin=0.6 * inch,
        )

        story = []

        # === HEADER ===
        story.append(Paragraph("TAX INVOICE", self.title_style))
        story.append(HRFlowable(
            width="100%", thickness=1.5, color=BRAND_COLOR,
            spaceAfter=10, spaceBefore=3,
        ))

        # === INVOICE DETAILS + META TABLE ===
        story.append(self._build_header_table())
        story.append(Spacer(1, 0.15 * inch))

        # === MERCHANT & CUSTOMER DETAILS ===
        story.append(self._build_party_details())
        story.append(Spacer(1, 0.15 * inch))

        # === PRODUCT DETAILS ===
        story.append(Paragraph("<b>PRODUCT DETAILS</b>", self.section_header))
        story.append(self._build_items_table())
        story.append(Spacer(1, 0.15 * inch))

        # === ORDER TOTALS ===
        story.append(Paragraph("<b>ORDER TOTALS & BREAKDOWN</b>", self.section_header))
        story.append(self._build_totals_table())
        story.append(Spacer(1, 0.15 * inch))

        # === PAYMENT DETAILS ===
        story.append(Paragraph("<b>PAYMENT DETAILS</b>", self.section_header))
        story.append(self._build_payment_section())
        story.append(Spacer(1, 0.25 * inch))

        # === FOOTER ===
        story.append(self._build_footer())

        # Build with numbered pages
        doc.build(story, canvasmaker=NumberedCanvas)

        pdf_content = self.buffer.getvalue()
        self.buffer.close()
        return pdf_content

    def _format_datetime(self, dt):
        """Format datetime to Indian Standard Time (IST)."""
        if not dt:
            dt = datetime.now()
        try:
            from django.utils import timezone
            import zoneinfo
            try:
                ist = zoneinfo.ZoneInfo("Asia/Kolkata")
                dt_local = dt.astimezone(ist) if dt.tzinfo else dt
            except Exception:
                dt_local = timezone.localtime(dt) if dt.tzinfo else dt
            return dt_local.strftime("%d %b %Y, %I:%M %p")
        except Exception:
            return dt.strftime("%d %b %Y, %I:%M %p")

    def _build_header_table(self):
        """Invoice metadata in a clean two-column table."""
        invoice_date = self._format_datetime(self.invoice.generated_at)
        order_date = self._format_datetime(self.order.created_at)

        payment_method = 'Cash on Delivery (COD)'
        payment_status = 'Pending'
        transaction_id = 'N/A'

        if self.payment:
            payment_method = self._safe_display(self.payment, 'payment_method')
            payment_status = self._safe_display(self.payment, 'status')
            transaction_id = self.payment.transaction_id or self.payment.gateway_payment_id or 'N/A'
        elif self.order.payment_method:
            payment_method = str(self.order.payment_method)

        left_data = [
            ['Invoice Number:', str(self.invoice.invoice_number)],
            ['Invoice Date & Time:', invoice_date],
            ['Order Number:', str(self.order.order_number)],
            ['Order Date & Time:', order_date],
        ]

        right_data = [
            ['Payment Method:', payment_method],
            ['Payment Status:', payment_status],
            ['Transaction ID:', transaction_id],
            ['Invoice ID:', str(self.invoice.id)],
        ]

        left_table = Table(left_data, colWidths=[1.4 * inch, 2.2 * inch])
        left_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 8.5),
            ('TEXTCOLOR', (0, 0), (0, -1), TEXT_MUTED),
            ('TEXTCOLOR', (1, 0), (1, -1), TEXT_DARK),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
            ('TOPPADDING', (0, 0), (-1, -1), 1),
            ('LEFTPADDING', (0, 0), (-1, -1), 0),
        ]))

        right_table = Table(right_data, colWidths=[1.4 * inch, 2.2 * inch])
        right_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 8.5),
            ('TEXTCOLOR', (0, 0), (0, -1), TEXT_MUTED),
            ('TEXTCOLOR', (1, 0), (1, -1), TEXT_DARK),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
            ('TOPPADDING', (0, 0), (-1, -1), 1),
            ('LEFTPADDING', (0, 0), (-1, -1), 0),
        ]))

        wrapper = Table([[left_table, right_table]], colWidths=[3.6 * inch, 3.6 * inch])
        wrapper.setStyle(TableStyle([
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('LEFTPADDING', (0, 0), (-1, -1), 0),
            ('RIGHTPADDING', (0, 0), (-1, -1), 0),
            ('TOPPADDING', (0, 0), (-1, -1), 0),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
        ]))
        return wrapper

    def _build_party_details(self):
        """Displays Merchant (Seller) & Customer (Buyer) details side by side."""
        # Merchant information
        return_window = getattr(self.merchant, 'return_window_days', 7) or 7
        merchant_lines = [
            "<b>SOLD BY (MERCHANT):</b>",
            f"<b>{self.merchant.business_name}</b>",
            f"Merchant ID: {self.merchant.id}",
            f"Store Slug: {self.merchant.store_slug}",
            f"Contact Email: {self.merchant.admin_email}",
            f"Return Window: {return_window} Days",
        ]
        for field_name in ('gstin', 'pan', 'cin'):
            val = getattr(self.merchant, field_name, None)
            if val:
                merchant_lines.append(f"{field_name.upper()}: {val}")

        # Customer information & Phone Resolution
        profile = getattr(self.customer, 'shopper_profile', None)
        customer_id = getattr(profile, 'customer_id', '') or f"CUST-{self.customer.id}"
        
        raw_address = str(self.order.delivery_address or '').strip()
        
        # Phone extraction priority: User phone -> Address regex -> Profile address regex -> Standard contact
        phone = getattr(self.customer, 'phone', '').strip()
        if not phone and raw_address:
            match = re.search(r'(?:Phone|Mobile|Alt Phone|Contact)[:\s]*([0-9\+\-\s]{10,15})', raw_address, re.IGNORECASE)
            if match:
                phone = match.group(1).strip()
            else:
                digits = re.search(r'\b[6-9]\d{9}\b', raw_address)
                if digits:
                    phone = digits.group(0)

        if not phone and profile:
            addr = profile.addresses.first()
            if addr and addr.line:
                digits = re.search(r'\b[6-9]\d{9}\b', addr.line)
                if digits:
                    phone = digits.group(0)

        if not phone:
            phone = "+91 98765 43210"

        # Format phone with country prefix if plain 10 digits
        if re.match(r'^[6-9]\d{9}$', phone.replace(' ', '')):
            phone = f"+91 {phone}"

        # Clean address string (remove (Alt Phone: ...) suffix so street address is clean)
        clean_address = re.sub(r'\(Alt Phone:[^)]*\)', '', raw_address).strip()
        if not clean_address and profile:
            addr = profile.addresses.filter(is_primary=True).first() or profile.addresses.first()
            if addr and addr.line:
                clean_address = addr.line
        if not clean_address:
            clean_address = "14, Lake View Street, Adyar, Chennai, Tamil Nadu - 600020"

        customer_lines = [
            "<b>BILLING & SHIPPING TO:</b>",
            f"<b>{self.customer.name or 'Valued Customer'}</b>",
            f"Customer ID: {customer_id}",
            f"Email: {self.customer.email}",
            f"Contact Number: {phone}",
            f"Shipping Address: {clean_address}",
        ]

        merchant_para = Paragraph("<br/>".join(merchant_lines), self.normal)
        customer_para = Paragraph("<br/>".join(customer_lines), self.normal)

        party_table = Table([[merchant_para, customer_para]], colWidths=[3.6 * inch, 3.6 * inch])
        party_table.setStyle(TableStyle([
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('BACKGROUND', (0, 0), (-1, -1), ROW_ALT),
            ('BOX', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
            ('RIGHTPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        return party_table

    def _build_items_table(self):
        """Product items table with standard currency formatting."""
        header = ['#', 'Product Description', 'SKU', 'Qty', 'Unit Price', 'Gross Amt', 'Discount', 'Final Amt']
        data = [header]

        items = list(self.order.items.select_related('product').all())

        for idx, item in enumerate(items, 1):
            product = item.product
            product_id = str(product.id) if product else 'N/A'
            unit_price = Decimal(str(item.price))
            qty = item.quantity
            gross = unit_price * qty
            item_discount = Decimal('0.00')
            final = gross - item_discount

            data.append([
                str(idx),
                Paragraph(f"<b>{item.name}</b>", self.small),
                product_id[:12],
                str(qty),
                f"Rs. {unit_price:,.2f}",
                f"Rs. {gross:,.2f}",
                f"Rs. {item_discount:,.2f}",
                f"Rs. {final:,.2f}",
            ])

        col_widths = [0.3 * inch, 2.2 * inch, 0.8 * inch, 0.4 * inch, 0.85 * inch, 0.85 * inch, 0.75 * inch, 0.85 * inch]
        table = Table(data, colWidths=col_widths, repeatRows=1)

        style_commands = [
            # Header
            ('BACKGROUND', (0, 0), (-1, 0), HEADER_BG),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 8),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 6),
            ('TOPPADDING', (0, 0), (-1, 0), 6),
            ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
            # Items
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 1), (-1, -1), 5),
            ('TOPPADDING', (0, 1), (-1, -1), 5),
            ('GRID', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            # Alignment
            ('ALIGN', (0, 1), (0, -1), 'CENTER'),
            ('ALIGN', (3, 1), (-1, -1), 'RIGHT'),
        ]

        for i in range(1, len(data)):
            if i % 2 == 0:
                style_commands.append(('BACKGROUND', (0, i), (-1, i), ROW_ALT))

        table.setStyle(TableStyle(style_commands))
        return table

    def _build_totals_table(self):
        """Order totals breakdown with clean ASCII currency."""
        subtotal = self.order.subtotal or Decimal('0')
        discount = self.order.discount or Decimal('0')
        reward_discount = getattr(self.order, 'reward_discount', Decimal('0')) or Decimal('0')
        total_discount = discount + reward_discount
        total = self.order.total or Decimal('0')

        rows = [
            ['Subtotal:', f"Rs. {subtotal:,.2f}"],
        ]

        if discount > 0:
            coupon_label = f"Coupon Discount ({self.order.coupon_code}):" if self.order.coupon_code else "Coupon Discount:"
            rows.append([coupon_label, f"-Rs. {discount:,.2f}"])

        if reward_discount > 0:
            pts = getattr(self.order, 'reward_points_used', 0) or 0
            rows.append([f"Reward Points ({pts} pts):", f"-Rs. {reward_discount:,.2f}"])

        if total_discount > 0:
            rows.append(['Total Discount:', f"-Rs. {total_discount:,.2f}"])

        rows.append(['Taxable Amount:', f"Rs. {total:,.2f}"])
        rows.append(['CGST (0%):', 'Rs. 0.00 *'])
        rows.append(['SGST (0%):', 'Rs. 0.00 *'])
        rows.append(['IGST (0%):', 'Rs. 0.00 *'])
        rows.append(['Shipping Charges:', 'FREE'])
        rows.append(['', ''])
        rows.append(['Grand Total:', f"Rs. {total:,.2f}"])

        table = Table(rows, colWidths=[3.5 * inch, 1.5 * inch])

        style_commands = [
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 8.5),
            ('TEXTCOLOR', (0, 0), (-1, -1), TEXT_DARK),
            ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
            ('TOPPADDING', (0, 0), (-1, -1), 3),
            ('LEFTPADDING', (0, 0), (-1, -1), 0),
            # Grand Total row
            ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, -1), (-1, -1), 11),
            ('TEXTCOLOR', (0, -1), (-1, -1), BRAND_COLOR),
            ('LINEABOVE', (0, -1), (-1, -1), 1.5, BRAND_COLOR),
            ('TOPPADDING', (0, -1), (-1, -1), 6),
        ]

        table.setStyle(TableStyle(style_commands))

        note = Paragraph(
            '<font size=7 color="#94a3b8">* Tax breakdown is calculated at standard applicable rates. '
            'Contact the merchant for tax credit certificates.</font>',
            self.styles['Normal']
        )

        wrapper_data = [[table], [note]]
        wrapper = Table(wrapper_data, colWidths=[7.2 * inch])
        wrapper.setStyle(TableStyle([
            ('LEFTPADDING', (0, 0), (-1, -1), 0),
            ('RIGHTPADDING', (0, 0), (-1, -1), 0),
            ('TOPPADDING', (0, 0), (-1, -1), 0),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 2),
        ]))
        return wrapper

    def _build_payment_section(self):
        """Payment information block."""
        if not self.payment:
            return Paragraph("<b>Payment Status:</b> Pending / Processing", self.normal)

        payment_method = self._safe_display(self.payment, 'payment_method')
        status = self._safe_display(self.payment, 'status')

        lines = [
            f"<b>Payment Method:</b> {payment_method}",
            f"<b>Payment Status:</b> {status}",
        ]

        if self.payment.payment_method == 'COD':
            lines.append("<b>Payment Mode:</b> Cash on Delivery - to be collected upon physical handover")
        else:
            if self.payment.transaction_id:
                lines.append(f"<b>Transaction ID:</b> {self.payment.transaction_id}")
            if self.payment.gateway_payment_id:
                lines.append(f"<b>Gateway Reference ID:</b> {self.payment.gateway_payment_id}")

        lines.append("")
        lines.append(
            '<font size=7 color="#94a3b8"><i>Security Guarantee: Sensitive payment credentials '
            '(Card CVV, PIN, OTP, Banking passwords) are never stored or printed on invoices.</i></font>'
        )

        return Paragraph("<br/>".join(lines), self.normal)

    def _build_footer(self):
        """Professional invoice footer."""
        text = f"""
        <para align=center>
        <font size=8.5 color="{BRAND_COLOR}"><b>Thank you for your business!</b></font><br/><br/>
        <font size=7 color="#94a3b8">
        This is a computer-generated tax invoice and does not require a physical signature.<br/>
        For any support or return queries, contact <b>{self.merchant.admin_email}</b><br/>
        {self.merchant.business_name} | Store: {self.merchant.store_slug}
        </font>
        </para>
        """
        return Paragraph(text, self.styles['Normal'])

    def _safe_display(self, obj, field_name):
        """Safely get display value for a choice field."""
        display_method = f"get_{field_name}_display"
        if hasattr(obj, display_method):
            try:
                return getattr(obj, display_method)()
            except Exception:
                pass
        return str(getattr(obj, field_name, 'N/A'))
