# Generated by Django 5.1.15 on 2026-08-25 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_returnable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="original_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Original MRP for strike-through display",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=3),
        ),
        migrations.AddField(
            model_name="product",
            name="return_window_days",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="product",
            name="review_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=64, unique=True)),
                (
                    "size",
                    models.CharField(
                        help_text="e.g. S, M, L, XL, 8, 9, 10", max_length=32
                    ),
                ),
                ("color", models.CharField(blank=True, default="", max_length=64)),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "extra_price_delta",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Additional cost on top of base product price",
                        max_digits=10,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["product", "stock"],
                        name="catalog_pro_product_ee4f5c_idx",
                    )
                ],
                "unique_together": {("product", "size", "color")},
            },
        ),
    ]
