# Generated by Django 5.1.15 on 2026-08-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_is_returnable_product_original_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='exchange_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='inspection_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='max_replacements',
            field=models.PositiveIntegerField(default=1, help_text='Max replacements per order (CP24)'),
        ),
        migrations.AddField(
            model_name='category',
            name='non_returnable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='proof_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='refund_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='replacement_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='return_window_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='product',
            name='included_accessories',
            field=models.JSONField(default=list, help_text="List of accessories included with this product, e.g. ['Charger', 'Cable', 'Manual']"),
        ),
        migrations.AddField(
            model_name='product',
            name='total_returns_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this product has been returned'),
        ),
        migrations.AddField(
            model_name='product',
            name='total_sold_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this product has been sold'),
        ),
    ]
