# Generated by Django 5.1.15 on 2026-08-20 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("merchants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_number", models.CharField(max_length=32, unique=True)),
                ("customer_name", models.CharField(max_length=255)),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("COD", "Cash on Delivery"), ("Prepaid", "Prepaid")],
                        default="COD",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Active", "Active"),
                            ("Review", "Review"),
                            ("Confirmed", "Confirmed"),
                        ],
                        default="Pending",
                        max_length=16,
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("Processing", "Processing"),
                            ("Pending Review", "Pending Review"),
                            ("In Transit", "In Transit"),
                            ("Delivered", "Delivered"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Processing",
                        max_length=32,
                    ),
                ),
                ("risk_tier", models.CharField(default="Low", max_length=16)),
                (
                    "verification_status",
                    models.CharField(default="Verified", max_length=16),
                ),
                (
                    "verification_method",
                    models.CharField(default="device_only", max_length=16),
                ),
                (
                    "device_token",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("risk_context", models.TextField(blank=True, default="")),
                ("tracking_events", models.JSONField(default=list)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="merchants.merchant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
    ]
