# Generated by Django 5.1.15 on 2026-08-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_coupon_code_order_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Pending Review', 'Pending Review'), ('Awaiting payment', 'Awaiting payment'), ('Payment failed', 'Payment failed'), ('Payment rejected', 'Payment rejected'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Processing', max_length=32),
        ),
    ]
