# Generated by Django 5.1.15 on 2026-08-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_delivery_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reward_points_earned",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
