# Generated by Django 5.1.15 on 2026-08-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_reward_points_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_cod_refused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='risk_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='variant_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
