# Generated by Django 5.1.15 on 2026-08-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_order_is_cod_refused_order_risk_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("Processing", "Processing"),
                    ("Pending Review", "Pending Review"),
                    ("Awaiting payment", "Awaiting payment"),
                    ("Payment failed", "Payment failed"),
                    ("Payment rejected", "Payment rejected"),
                    ("In Transit", "In Transit"),
                    ("Delivered", "Delivered"),
                    ("Return Requested", "Return Requested"),
                    ("Return Approved", "Return Approved"),
                    ("Return Rejected", "Return Rejected"),
                    ("Product Returned", "Product Returned"),
                    ("Refund Processed", "Refund Processed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Processing",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Active", "Active"),
                    ("Review", "Review"),
                    ("Confirmed", "Confirmed"),
                    ("Delivered", "Delivered"),
                    ("Return Requested", "Return Requested"),
                    ("Return Approved", "Return Approved"),
                    ("Return Rejected", "Return Rejected"),
                    ("Product Returned", "Product Returned"),
                    ("Refund Processed", "Refund Processed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=32,
            ),
        ),
    ]
