# Generated by Django 5.1.15 on 2026-08-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_order_delivered_at_alter_order_delivery_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="variant_count",
        ),
        migrations.AddField(
            model_name="order",
            name="cancellation_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="cancellation_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_by",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
