# Generated by Django 5.1.15 on 2026-08-25 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_product_is_returnable_product_original_price_and_more"),
        ("orders", "0009_remove_order_variant_count_order_cancellation_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="is_final_sale",
            field=models.BooleanField(default=False, help_text="Non-returnable item"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="catalog.productvariant",
            ),
        ),
    ]
