# Generated by Django 5.1.15 on 2026-08-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderitem_is_final_sale_orderitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_accepted_open_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='open_box_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='barcode',
            field=models.CharField(blank=True, default='', help_text='Barcode scanned at shipment', max_length=128),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='imei_number',
            field=models.CharField(blank=True, default='', help_text='IMEI number for mobile devices', max_length=64),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='serial_number',
            field=models.CharField(blank=True, default='', help_text='Serial number recorded at time of shipment', max_length=128),
        ),
    ]
