# Generated by Django 5.1.15 on 2026-08-20 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("merchants", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("customer_name", models.CharField(max_length=255)),
                ("reason", models.CharField(max_length=64)),
                ("note", models.TextField(blank=True, default="")),
                ("risk_tier", models.CharField(default="Low", max_length=16)),
                ("risk_score", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("manual_review", "Manual Review"),
                        ],
                        default="manual_review",
                        max_length=16,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("auto_approved", "Auto Approved"),
                            ("pending_review", "Pending Review"),
                            ("legitimate_return", "Legitimate Return"),
                            ("confirmed_fraud", "Confirmed Fraud"),
                        ],
                        default="pending_review",
                        max_length=32,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(default="Pending", max_length=16),
                ),
                (
                    "verification_method",
                    models.CharField(default="unverified", max_length=16),
                ),
                ("risk_context", models.TextField(blank=True, default="")),
                ("signals", models.JSONField(default=list)),
                (
                    "pickup_slot",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "reviewed_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns",
                        to="merchants.merchant",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReturnLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.product",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_lines",
                        to="returns.returnrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReturnEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("at", models.DateTimeField(auto_now_add=True)),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="returns.returnrequest",
                    ),
                ),
            ],
            options={
                "ordering": ("at", "id"),
            },
        ),
        migrations.CreateModel(
            name="DoorstepProof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proof_type", models.CharField(default="signature", max_length=32)),
                ("file", models.FileField(blank=True, null=True, upload_to="proof/")),
                ("metadata", models.JSONField(default=dict)),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proofs",
                        to="returns.returnrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("approve", "Approve"), ("reject", "Reject")],
                        max_length=16,
                    ),
                ),
                ("reviewed_by", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "return_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_decision",
                        to="returns.returnrequest",
                    ),
                ),
            ],
        ),
    ]
