# Generated by Django 5.1.15 on 2026-08-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='proof_image_url',
            field=models.TextField(blank=True, default='', help_text='Unboxing photo / return proof image URL'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='proof_verified',
            field=models.BooleanField(default=False),
        ),
    ]
