# Generated by Django 5.1.15 on 2026-08-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("returns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnrequest",
            name="images",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="refund_method",
            field=models.CharField(
                choices=[
                    ("original", "Original Payment Method"),
                    ("store_credit", "Store Credit / Reward Points"),
                    ("bank_transfer", "Direct Bank Transfer / UPI"),
                ],
                default="original",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("auto_approved", "Auto Approved"),
                    ("pending_review", "Pending Review"),
                    ("legitimate_return", "Legitimate Return"),
                    ("confirmed_fraud", "Confirmed Fraud"),
                    ("product_returned", "Product Returned"),
                    ("refund_processed", "Refund Processed"),
                ],
                default="pending_review",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("manual_review", "Manual Review"),
                    ("product_returned", "Product Returned"),
                    ("refund_processed", "Refund Processed"),
                ],
                default="manual_review",
                max_length=32,
            ),
        ),
    ]
