# Generated by Django 5.1.15 on 2026-08-24 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_returnrequest_images_returnrequest_refund_method_and_more'),
        ('returns', '0002_returnrequest_proof_image_url_and_more'),
    ]

    operations = [
    ]
