# Generated by Django 5.1.15 on 2026-08-25 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_product_is_returnable_product_original_price_and_more"),
        ("orders", "0010_orderitem_is_final_sale_orderitem_variant"),
        ("returns", "0003_merge_20260824_1954"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnrequest",
            name="driver_name",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="driver_phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="estimated_arrival_window",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="exchange_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exchange_returns",
                to="catalog.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="returns",
                to="orders.orderitem",
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="refund_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="type",
            field=models.CharField(
                choices=[
                    ("EXCHANGE", "Smart Exchange"),
                    ("REFUND", "Refund"),
                    ("STORE_CREDIT", "Store Credit"),
                ],
                default="REFUND",
                max_length=16,
            ),
        ),
    ]
