# Generated by Django 5.1.15 on 2026-08-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0004_returnrequest_driver_name_returnrequest_driver_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='accessories_expected',
            field=models.JSONField(default=list, help_text='List of accessories that were shipped'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='accessories_missing',
            field=models.JSONField(default=list, help_text='List of missing accessories'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='accessories_returned',
            field=models.JSONField(default=list, help_text='List of accessories actually returned'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='checkpoint_signals',
            field=models.JSONField(default=list, help_text='Detailed per-checkpoint scoring breakdown'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='imei_mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='is_product_swap_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='original_reason',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='packaging_condition',
            field=models.CharField(choices=[('original_intact', 'Original Packaging — Intact'), ('original_damaged', 'Original Packaging — Damaged'), ('different_box', 'Different / Wrong Packaging'), ('no_packaging', 'No Packaging'), ('not_inspected', 'Not Yet Inspected')], default='not_inspected', max_length=32),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='product_condition',
            field=models.CharField(choices=[('unused', 'Unused'), ('used', 'Used'), ('damaged', 'Damaged'), ('soiled', 'Soiled'), ('tampered', 'Tampered / Seal Broken'), ('tag_removed', 'Return Tag Removed'), ('unknown', 'Unknown / Not Inspected')], default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='quantity_claimed',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='quantity_received',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='reason_change_history',
            field=models.JSONField(default=list, help_text='History of reason changes'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='reason_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='returned_imei_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='returned_serial_number',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='serial_mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='shopper_imei_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='shopper_reported_condition',
            field=models.CharField(choices=[('unused', 'Unused'), ('used', 'Used'), ('damaged', 'Damaged'), ('soiled', 'Soiled'), ('tampered', 'Tampered / Seal Broken'), ('tag_removed', 'Return Tag Removed'), ('unknown', 'Unknown / Not Inspected')], default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='shopper_serial_number',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='swap_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='verification_images',
            field=models.JSONField(default=list, help_text='Photos taken during verification'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='verification_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='verified_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('manual_review', 'Manual Review'), ('product_returned', 'Product Returned'), ('refund_processed', 'Refund Processed'), ('hold', 'Hold — Awaiting Verification')], default='manual_review', max_length=32),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='type',
            field=models.CharField(choices=[('EXCHANGE', 'Smart Exchange'), ('REFUND', 'Refund'), ('STORE_CREDIT', 'Store Credit'), ('REPLACEMENT', 'Replacement')], default='REFUND', max_length=16),
        ),
    ]
