# Generated by Django 5.1.15 on 2026-08-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='return_window_days',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
