# Generated by Django 5.1.15 on 2026-08-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_merchant_return_window_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='merchant_username',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
