# Generated by Django 5.1.15 on 2026-08-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("merchants", "0003_merchant_merchant_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="merchant",
            name="city",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="merchant",
            name="gstin",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="merchant",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="merchant",
            name="pincode",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="merchant",
            name="state",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
