# Generated by Django 5.1.15 on 2026-08-21 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='otpchallenge',
            name='purpose',
            field=models.CharField(default='verification', max_length=32),
        ),
        migrations.AddField(
            model_name='otpchallenge',
            name='role',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddIndex(
            model_name='otpchallenge',
            index=models.Index(fields=['user', 'purpose', 'created_at'], name='verificatio_user_id_69089f_idx'),
        ),
        migrations.AddIndex(
            model_name='otpchallenge',
            index=models.Index(fields=['target', 'purpose', 'created_at'], name='verificatio_target_5d8a74_idx'),
        ),
    ]
