# Generated by Django 5.1.15 on 2026-08-24 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0001_initial'),
        ('merchants', '0003_merchant_merchant_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerriskprofile',
            name='confirmed_violations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerriskprofile',
            name='escalation_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Normal'), (1, 'Warning / Verification'), (2, 'COD Restricted'), (3, 'Prepaid + Manual Review'), (4, 'Temporary Account Restriction'), (5, 'Merchant Final Review')], default=0),
        ),
        migrations.AddField(
            model_name='customerriskprofile',
            name='restriction_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CustomerRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restriction_type', models.CharField(choices=[('cod_limit', 'COD Limit'), ('order_value_limit', 'Order Value Limit'), ('variant_limit', 'Variant Limit'), ('prepaid_only', 'Prepaid Only'), ('cod_suspended', 'COD Suspended'), ('account_restricted', 'Account Restricted'), ('high_value_restricted', 'High-Value Order Restricted')], max_length=32)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('removed', 'Removed by Merchant')], default='active', max_length=16)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, help_text='Optional cap value (e.g. max COD amount or max order value).', max_digits=12, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.CharField(default='system', max_length=255)),
                ('removed_by', models.CharField(blank=True, default='', max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_restrictions', to='merchants.merchant')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EscalationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_level', models.PositiveSmallIntegerField(default=0)),
                ('new_level', models.PositiveSmallIntegerField(default=0)),
                ('trigger_event', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_history', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_history', to='merchants.merchant')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
