# Generated by Django 5.1.15 on 2026-08-24 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0002_customerriskprofile_confirmed_violations_and_more'),
        ('merchants', '0003_merchant_merchant_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantListRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_type', models.CharField(choices=[('whitelist', 'VIP Whitelist (Bypass Risk Scoring)'), ('blacklist', 'Permanent Blacklist (Block Orders)')], default='blacklist', max_length=16)),
                ('entry_type', models.CharField(choices=[('email', 'Email Address'), ('phone', 'Phone Number'), ('device_token', 'Device Fingerprint / Token'), ('pincode', 'Pincode / Postal Area'), ('customer', 'Specific Customer ID')], default='email', max_length=16)),
                ('value', models.CharField(help_text='The email, phone, token, or pincode to match.', max_length=255)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(default='merchant', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_rules', to='merchants.merchant')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('merchant', 'rule_type', 'entry_type', 'value')},
            },
        ),
    ]
