# Generated by Django 5.1.15 on 2026-08-20 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("route", models.CharField(max_length=255)),
                ("pincode", models.CharField(blank=True, default="", max_length=16)),
                ("total_deliveries", models.PositiveIntegerField(default=0)),
                ("total_returns_handled", models.PositiveIntegerField(default=0)),
                ("return_rate", models.FloatField(default=0)),
                ("expected_return_rate", models.FloatField(default=0)),
                ("flagged_return_count", models.PositiveIntegerField(default=0)),
                ("risk_flag", models.CharField(default="Monitor", max_length=16)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_agents",
                        to="merchants.merchant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SelfTuningSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rule", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=255)),
                ("current_value", models.FloatField()),
                ("suggested_value", models.FloatField()),
                ("reason", models.TextField(blank=True, default="")),
                ("confidence", models.FloatField(default=0)),
                ("sample_size", models.PositiveIntegerField(default=0)),
                ("window_days", models.PositiveIntegerField(default=14)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suggested", "Suggested"),
                            ("applied", "Applied"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="suggested",
                        max_length=16,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="self_tuning_suggestions",
                        to="merchants.merchant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
