# Generated by Django 5.1.15 on 2026-08-25 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryagent",
            name="avatar_url",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="deliveryagent",
            name="current_risk_level",
            field=models.CharField(
                choices=[("HIGH", "High"), ("MEDIUM", "Medium"), ("LOW", "Low")],
                default="MEDIUM",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="deliveryagent",
            name="is_under_investigation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deliveryagent",
            name="location_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.CreateModel(
            name="AgentActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ANOMALY_DETECTED", "Anomaly Detected"),
                            ("INVESTIGATION_STARTED", "Investigation Started"),
                            ("HUMAN_SIGN_OFF", "Human Sign-off"),
                            ("BASELINE_UPDATED", "Baseline Updated"),
                            ("FLAGGED", "Flagged for Review"),
                        ],
                        default="ANOMALY_DETECTED",
                        max_length=32,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="admin_api.deliveryagent",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AgentRiskSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_deliveries", models.PositiveIntegerField(default=0)),
                ("total_returns", models.PositiveIntegerField(default=0)),
                ("flagged_count", models.PositiveIntegerField(default=0)),
                ("actual_return_rate", models.FloatField(default=0.0)),
                ("expected_baseline_rate", models.FloatField(default=0.0)),
                ("anomaly_gap", models.FloatField(default=0.0)),
                ("status_note", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_snapshots",
                        to="admin_api.deliveryagent",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
