# Generated by Django 5.1.15 on 2026-08-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='paymentevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='paymentevent',
            name='unique_payment_event',
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_demo_payment',
            field=models.BooleanField(default=True, help_text='True for simulated payments'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_details',
            field=models.JSONField(blank=True, default=dict, help_text='Store UPI ID, last 4 digits of card, bank name, etc.'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('UPI', 'UPI'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('NET_BANKING', 'Net Banking'), ('MOBILE_BANKING', 'Mobile Banking')], default='COD', max_length=32),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, default='', help_text='Demo transaction ID for display', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='paymentevent',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_event_id__gt', '')), fields=('payment', 'gateway_event_id'), name='unique_payment_event'),
        ),
    ]
